language: rust
dist: trusty
sudo: false
cache: cargo
os:
  - linux
  - osx
rust:
  - nightly
matrix:
  include:
  - rust: nightly
    os: linux
  allow_failures:
  - os: osx
  fast_finish: true
install:
    # Required for Racer autoconfiguration
    rustup component add rust-src
script: |
  #!/bin/bash
  # compile #[cfg(not(test))] code
  cargo build --verbose
  cargo test --verbose
