[package]
name = "hyper_server"
version = "0.1.0"
authors = ["Jonathan Turner <jturner@mozilla.com>"]

[dependencies]
futures = { git = "https://github.com/alexcrichton/futures-rs" }
log = "0.3.6"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
tokio-hyper = { git = "https://github.com/tokio-rs/tokio-hyper" }
racer = { git = "https://github.com/phildawes/racer" }
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"

[dev-dependencies]
env_logger = "0.3.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
default-features = false
