[workspace]
members = [
    "rls",
    "vfs",
    "analysis",
    "data",
    "span",
    "languageserver-types",
]

[replace]
"rls-data:0.7.0" = { path = "data" }
"rls-span:0.4.0" = { path = "span" }
