[package]
name = "rls"
version = "0.129.0"
authors = ["Nick Cameron <ncameron@mozilla.com>", "The RLS developers"]
description = "Rust Language Server - provides information about Rust programs to IDEs and other tools"
license = "Apache-2.0/MIT"
repository = "https://github.com/rust-lang-nursery/rls"
categories = ["development-tools"]

build = "build.rs"

[dependencies]
cargo = { git = "https://github.com/rust-lang/cargo", rev = "e2348c2db296ce33428933c3ab8786d5f3c54a2e" }
cargo_metadata = "0.5.2"
clippy_lints = { version = "0.0.207", optional = true }
env_logger = "0.5"
failure = "0.1.1"
itertools = "0.7.3"
jsonrpc-core = "8.0.1"
languageserver-types = "0.43"
lazy_static = "1"
log = "0.4"
num_cpus = "1"
racer = "2.0.14"
rayon = "1"
rls-analysis = "0.13"
rls-blacklist = "0.1.2"
rls-data = { version = "0.16", features = ["serialize-serde"] }
rls-rustc = "0.4.0"
rls-span = { version = "0.4", features = ["serialize-serde"] }
rls-vfs = { version = "0.4.5", features = ["racer-impls"] }
rustfmt-nightly = { git = "https://github.com/rust-lang-nursery/rustfmt", rev = "5c1884eacf791722e2d06d8e1eb113bc9207492b" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.1.0"
walkdir = "2.1"
regex = "1"
ordslice = "0.3"

[dev-dependencies]
json = "0.11"

[features]
default = []
clippy = ["clippy_lints"]
